---
name: Component Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  component-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.6.2'

    - name: Install dependencies
      run: npm install

    - name: Component tests
      run: npm run cy:component
