name: Component Test

on:
  push:
    branches:
      - component-test-patch-1

jobs:
  component-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.6.2'

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &

    - name: Run Cypress component tests
      run: npm run test:comp
