name: End-to-End Test

on:
  push:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &

    - name: Wait for application to start
      run: sleep 30

    - name: Run Cypress end-to-end tests
      run: npm run cypress:run:e2e
