---
name: End-to-End Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.6.2'

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &

    - name: Wait for application to start
      run: sleep 10

    - name: End-to-End tests
      run: npm run cypress:run:e2e
